### ISSUE TITLE
Should we get rid of the Harmony Generators requirement?

### ISSUE THREAD

**Issue by JonGretar** [JonGretar/ResourceMachine#1]
This version of Resource Machine currently depends on Harmony Generators.

This is only because that this was the first method I could think of that allows me to traverse the decision tree without making the stack trace look insane. Debuggability is important to me and having a usable stack trace is a strong requirement.

**Comment by jmar777** [comment]
It's probably worth noting that with v0.12.0 being so close to release, avoiding generators as a dependency is becoming increasingly less important. #twocents

**Comment by JonGretar** [comment]
Yes it's less important.
It will not be enabled by default though. You will still need to use the `--harmony` flag until V8 enables it by default.

However one might just go with it and commit to it. Other parts in the library could benefit from Harmony magic.
